-- Extend SalesChannel enum with additional distribution channels.
ALTER TYPE "SalesChannel" ADD VALUE IF NOT EXISTS 'PROMOTER';
ALTER TYPE "SalesChannel" ADD VALUE IF NOT EXISTS 'COURTESY';
ALTER TYPE "SalesChannel" ADD VALUE IF NOT EXISTS 'CORPORATE';
ALTER TYPE "SalesChannel" ADD VALUE IF NOT EXISTS 'MOBILE';
ALTER TYPE "SalesChannel" ADD VALUE IF NOT EXISTS 'PHONE';
ALTER TYPE "SalesChannel" ADD VALUE IF NOT EXISTS 'INVITATION';
ALTER TYPE "SalesChannel" ADD VALUE IF NOT EXISTS 'AFFILIATE';
ALTER TYPE "SalesChannel" ADD VALUE IF NOT EXISTS 'VIP';
ALTER TYPE "SalesChannel" ADD VALUE IF NOT EXISTS 'RESALE';

-- Extend UserRole for taquilla supervision hierarchy.
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'TAQUILLA_SUPERVISOR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'TAQUILLA_ADMIN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'FINANCE';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'MARKETING';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SUPPORT';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'AUDITOR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'AFFILIATE';
